
package com.ttc.ch2.api.ccapi.v3;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ccapiService", targetNamespace = "http://www.ttc.com/ch2/api/ccapi/v3", wsdlLocation = "https://content-dev.corp.ttc:443/ccapi/v3/CCAPIv3.wsdl")
public class CcapiService
    extends Service
{

    private final static URL CCAPISERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ttc.ch2.api.ccapi.v3.CcapiService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ttc.ch2.api.ccapi.v3.CcapiService.class.getResource(".");
            url = new URL(baseUrl, "https://content-dev.corp.ttc:443/ccapi/v3/CCAPIv3.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://content-dev.corp.ttc:443/ccapi/v3/CCAPIv3.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CCAPISERVICE_WSDL_LOCATION = url;
    }

    public CcapiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CcapiService() {
        super(CCAPISERVICE_WSDL_LOCATION, new QName("http://www.ttc.com/ch2/api/ccapi/v3", "ccapiService"));
    }

    /**
     * 
     * @return
     *     returns Ccapi
     */
    @WebEndpoint(name = "ccapiSoap11")
    public Ccapi getCcapiSoap11() {
        return super.getPort(new QName("http://www.ttc.com/ch2/api/ccapi/v3", "ccapiSoap11"), Ccapi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ccapi
     */
    @WebEndpoint(name = "ccapiSoap11")
    public Ccapi getCcapiSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ttc.com/ch2/api/ccapi/v3", "ccapiSoap11"), Ccapi.class, features);
    }

}
