//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.aggregatedtours._2014._05._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CataloguedTourCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CataloguedTourName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToursList" type="{http://schema.ch2.ttc.com/AggregatedTours/2014/05/3.0}Tour" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cataloguedTourCode",
    "cataloguedTourName",
    "toursList"
})
@XmlRootElement(name = "AggregatedTours")
public class AggregatedTours {

    @XmlElement(name = "CataloguedTourCode", required = true)
    protected String cataloguedTourCode;
    @XmlElement(name = "CataloguedTourName", required = true)
    protected String cataloguedTourName;
    @XmlElement(name = "ToursList", required = true)
    protected List<Tour> toursList;

    /**
     * Gets the value of the cataloguedTourCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCataloguedTourCode() {
        return cataloguedTourCode;
    }

    /**
     * Sets the value of the cataloguedTourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCataloguedTourCode(String value) {
        this.cataloguedTourCode = value;
    }

    /**
     * Gets the value of the cataloguedTourName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCataloguedTourName() {
        return cataloguedTourName;
    }

    /**
     * Sets the value of the cataloguedTourName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCataloguedTourName(String value) {
        this.cataloguedTourName = value;
    }

    /**
     * Gets the value of the toursList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toursList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToursList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tour }
     * 
     * 
     */
    public List<Tour> getToursList() {
        if (toursList == null) {
            toursList = new ArrayList<Tour>();
        }
        return this.toursList;
    }

}
