//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.aggregatedtours._2014._05._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.ttc.ch2.schema.tourdeparturessimp._2014._04._3.TourDeparturesSimpType;
import com.ttc.ch2.schema.tourinfosimp._2014._01._3.TourInfoSimp;


/**
 * <p>Java class for Tour complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tour">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}TourDeparturesSimp"/>
 *         &lt;element ref="{http://schema.ch2.ttc.com/TourInfoSimp/2014/01/3.0}TourInfoSimp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tour", propOrder = {
    "tourDeparturesSimp",
    "tourInfoSimp"
})
public class Tour {

    @XmlElement(name = "TourDeparturesSimp", namespace = "http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0", required = true)
    protected TourDeparturesSimpType tourDeparturesSimp;
    @XmlElement(name = "TourInfoSimp", namespace = "http://schema.ch2.ttc.com/TourInfoSimp/2014/01/3.0", required = true)
    protected TourInfoSimp tourInfoSimp;

    /**
     * Gets the value of the tourDeparturesSimp property.
     * 
     * @return
     *     possible object is
     *     {@link TourDeparturesSimpType }
     *     
     */
    public TourDeparturesSimpType getTourDeparturesSimp() {
        return tourDeparturesSimp;
    }

    /**
     * Sets the value of the tourDeparturesSimp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TourDeparturesSimpType }
     *     
     */
    public void setTourDeparturesSimp(TourDeparturesSimpType value) {
        this.tourDeparturesSimp = value;
    }

    /**
     * Gets the value of the tourInfoSimp property.
     * 
     * @return
     *     possible object is
     *     {@link TourInfoSimp }
     *     
     */
    public TourInfoSimp getTourInfoSimp() {
        return tourInfoSimp;
    }

    /**
     * Sets the value of the tourInfoSimp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TourInfoSimp }
     *     
     */
    public void setTourInfoSimp(TourInfoSimp value) {
        this.tourInfoSimp = value;
    }

}
