//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttsl.marketvariationdepartureinfo._2010._09._1;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AssociatedInsurance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedInsurance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdditionalPricePerFamily" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AdditionalPricePerPartner" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AdditionalPricePerSingle" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="IsForcedButRemovable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsMandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MvAssociatedProductID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="PricePerFamilyCoverType" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PricePerPartnerCoverType" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PricePerSingleCoverType" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ProductDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ValueOfTourUpTo" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedInsurance", propOrder = {
    "additionalPricePerFamily",
    "additionalPricePerPartner",
    "additionalPricePerSingle",
    "code",
    "currencyCode",
    "endDate",
    "id",
    "isForcedButRemovable",
    "isMandatory",
    "mvAssociatedProductID",
    "pricePerFamilyCoverType",
    "pricePerPartnerCoverType",
    "pricePerSingleCoverType",
    "productDescription",
    "productName",
    "startDate",
    "valueOfTourUpTo"
})
public class AssociatedInsurance {

    @XmlElement(name = "AdditionalPricePerFamily")
    protected BigDecimal additionalPricePerFamily;
    @XmlElement(name = "AdditionalPricePerPartner")
    protected BigDecimal additionalPricePerPartner;
    @XmlElement(name = "AdditionalPricePerSingle")
    protected BigDecimal additionalPricePerSingle;
    @XmlElementRef(name = "Code", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> code;
    @XmlElementRef(name = "CurrencyCode", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> currencyCode;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "Id")
    protected Long id;
    @XmlElement(name = "IsForcedButRemovable")
    protected Boolean isForcedButRemovable;
    @XmlElement(name = "IsMandatory")
    protected Boolean isMandatory;
    @XmlElement(name = "MvAssociatedProductID")
    protected Long mvAssociatedProductID;
    @XmlElement(name = "PricePerFamilyCoverType")
    protected BigDecimal pricePerFamilyCoverType;
    @XmlElement(name = "PricePerPartnerCoverType")
    protected BigDecimal pricePerPartnerCoverType;
    @XmlElement(name = "PricePerSingleCoverType")
    protected BigDecimal pricePerSingleCoverType;
    @XmlElementRef(name = "ProductDescription", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> productDescription;
    @XmlElementRef(name = "ProductName", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> productName;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "ValueOfTourUpTo")
    protected BigDecimal valueOfTourUpTo;

    /**
     * Gets the value of the additionalPricePerFamily property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdditionalPricePerFamily() {
        return additionalPricePerFamily;
    }

    /**
     * Sets the value of the additionalPricePerFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdditionalPricePerFamily(BigDecimal value) {
        this.additionalPricePerFamily = value;
    }

    /**
     * Gets the value of the additionalPricePerPartner property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdditionalPricePerPartner() {
        return additionalPricePerPartner;
    }

    /**
     * Sets the value of the additionalPricePerPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdditionalPricePerPartner(BigDecimal value) {
        this.additionalPricePerPartner = value;
    }

    /**
     * Gets the value of the additionalPricePerSingle property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdditionalPricePerSingle() {
        return additionalPricePerSingle;
    }

    /**
     * Sets the value of the additionalPricePerSingle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdditionalPricePerSingle(BigDecimal value) {
        this.additionalPricePerSingle = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCode(JAXBElement<String> value) {
        this.code = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrencyCode(JAXBElement<String> value) {
        this.currencyCode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the isForcedButRemovable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsForcedButRemovable() {
        return isForcedButRemovable;
    }

    /**
     * Sets the value of the isForcedButRemovable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsForcedButRemovable(Boolean value) {
        this.isForcedButRemovable = value;
    }

    /**
     * Gets the value of the isMandatory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMandatory() {
        return isMandatory;
    }

    /**
     * Sets the value of the isMandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMandatory(Boolean value) {
        this.isMandatory = value;
    }

    /**
     * Gets the value of the mvAssociatedProductID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMvAssociatedProductID() {
        return mvAssociatedProductID;
    }

    /**
     * Sets the value of the mvAssociatedProductID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMvAssociatedProductID(Long value) {
        this.mvAssociatedProductID = value;
    }

    /**
     * Gets the value of the pricePerFamilyCoverType property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPricePerFamilyCoverType() {
        return pricePerFamilyCoverType;
    }

    /**
     * Sets the value of the pricePerFamilyCoverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPricePerFamilyCoverType(BigDecimal value) {
        this.pricePerFamilyCoverType = value;
    }

    /**
     * Gets the value of the pricePerPartnerCoverType property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPricePerPartnerCoverType() {
        return pricePerPartnerCoverType;
    }

    /**
     * Sets the value of the pricePerPartnerCoverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPricePerPartnerCoverType(BigDecimal value) {
        this.pricePerPartnerCoverType = value;
    }

    /**
     * Gets the value of the pricePerSingleCoverType property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPricePerSingleCoverType() {
        return pricePerSingleCoverType;
    }

    /**
     * Sets the value of the pricePerSingleCoverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPricePerSingleCoverType(BigDecimal value) {
        this.pricePerSingleCoverType = value;
    }

    /**
     * Gets the value of the productDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProductDescription() {
        return productDescription;
    }

    /**
     * Sets the value of the productDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProductDescription(JAXBElement<String> value) {
        this.productDescription = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProductName(JAXBElement<String> value) {
        this.productName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the valueOfTourUpTo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValueOfTourUpTo() {
        return valueOfTourUpTo;
    }

    /**
     * Sets the value of the valueOfTourUpTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValueOfTourUpTo(BigDecimal value) {
        this.valueOfTourUpTo = value;
    }

}
