//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttsl.marketvariationdepartureinfo._2010._09._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Brochure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Brochure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BrandCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BrochureCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BrochureId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="BrochureName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BrochureYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LongDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumberOfPages" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="OperatingPeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="OperatingPeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SellingCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SellingPeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SellingPeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ShortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Brochure", propOrder = {
    "brandCode",
    "brochureCode",
    "brochureId",
    "brochureName",
    "brochureYear",
    "longDescription",
    "numberOfPages",
    "operatingPeriodEndDate",
    "operatingPeriodStartDate",
    "sellingCompanyCode",
    "sellingPeriodEndDate",
    "sellingPeriodStartDate",
    "shortDescription"
})
public class Brochure {

    @XmlElementRef(name = "BrandCode", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> brandCode;
    @XmlElementRef(name = "BrochureCode", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> brochureCode;
    @XmlElement(name = "BrochureId")
    protected Long brochureId;
    @XmlElementRef(name = "BrochureName", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> brochureName;
    @XmlElementRef(name = "BrochureYear", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> brochureYear;
    @XmlElementRef(name = "LongDescription", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> longDescription;
    @XmlElement(name = "NumberOfPages")
    protected Integer numberOfPages;
    @XmlElement(name = "OperatingPeriodEndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar operatingPeriodEndDate;
    @XmlElement(name = "OperatingPeriodStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar operatingPeriodStartDate;
    @XmlElementRef(name = "SellingCompanyCode", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> sellingCompanyCode;
    @XmlElement(name = "SellingPeriodEndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sellingPeriodEndDate;
    @XmlElement(name = "SellingPeriodStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sellingPeriodStartDate;
    @XmlElementRef(name = "ShortDescription", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<String> shortDescription;

    /**
     * Gets the value of the brandCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBrandCode() {
        return brandCode;
    }

    /**
     * Sets the value of the brandCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBrandCode(JAXBElement<String> value) {
        this.brandCode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the brochureCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBrochureCode() {
        return brochureCode;
    }

    /**
     * Sets the value of the brochureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBrochureCode(JAXBElement<String> value) {
        this.brochureCode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the brochureId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBrochureId() {
        return brochureId;
    }

    /**
     * Sets the value of the brochureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBrochureId(Long value) {
        this.brochureId = value;
    }

    /**
     * Gets the value of the brochureName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBrochureName() {
        return brochureName;
    }

    /**
     * Sets the value of the brochureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBrochureName(JAXBElement<String> value) {
        this.brochureName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the brochureYear property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBrochureYear() {
        return brochureYear;
    }

    /**
     * Sets the value of the brochureYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBrochureYear(JAXBElement<String> value) {
        this.brochureYear = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the longDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLongDescription() {
        return longDescription;
    }

    /**
     * Sets the value of the longDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLongDescription(JAXBElement<String> value) {
        this.longDescription = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the numberOfPages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfPages() {
        return numberOfPages;
    }

    /**
     * Sets the value of the numberOfPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfPages(Integer value) {
        this.numberOfPages = value;
    }

    /**
     * Gets the value of the operatingPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperatingPeriodEndDate() {
        return operatingPeriodEndDate;
    }

    /**
     * Sets the value of the operatingPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperatingPeriodEndDate(XMLGregorianCalendar value) {
        this.operatingPeriodEndDate = value;
    }

    /**
     * Gets the value of the operatingPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperatingPeriodStartDate() {
        return operatingPeriodStartDate;
    }

    /**
     * Sets the value of the operatingPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperatingPeriodStartDate(XMLGregorianCalendar value) {
        this.operatingPeriodStartDate = value;
    }

    /**
     * Gets the value of the sellingCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSellingCompanyCode() {
        return sellingCompanyCode;
    }

    /**
     * Sets the value of the sellingCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSellingCompanyCode(JAXBElement<String> value) {
        this.sellingCompanyCode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the sellingPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSellingPeriodEndDate() {
        return sellingPeriodEndDate;
    }

    /**
     * Sets the value of the sellingPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSellingPeriodEndDate(XMLGregorianCalendar value) {
        this.sellingPeriodEndDate = value;
    }

    /**
     * Gets the value of the sellingPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSellingPeriodStartDate() {
        return sellingPeriodStartDate;
    }

    /**
     * Sets the value of the sellingPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSellingPeriodStartDate(XMLGregorianCalendar value) {
        this.sellingPeriodStartDate = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setShortDescription(JAXBElement<String> value) {
        this.shortDescription = ((JAXBElement<String> ) value);
    }

}
