//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttsl.marketvariationdepartureinfo._2010._09._1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketVariationPricing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketVariationPricing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="SellingCompanyCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AdultPortTax" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="AirPriceIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ChildPortTax" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="FoodFundPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="PriceIsIndicative" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketVariationPricing")
public class MarketVariationPricing {

    @XmlAttribute(name = "SellingCompanyCode", required = true)
    protected String sellingCompanyCode;
    @XmlAttribute(name = "AdultPortTax")
    protected BigDecimal adultPortTax;
    @XmlAttribute(name = "AirPriceIncluded")
    protected Boolean airPriceIncluded;
    @XmlAttribute(name = "ChildPortTax")
    protected BigDecimal childPortTax;
    @XmlAttribute(name = "FoodFundPrice")
    protected BigDecimal foodFundPrice;
    @XmlAttribute(name = "PriceIsIndicative")
    protected Boolean priceIsIndicative;
    @XmlAttribute(name = "Currency")
    protected String currency;

    /**
     * Gets the value of the sellingCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellingCompanyCode() {
        return sellingCompanyCode;
    }

    /**
     * Sets the value of the sellingCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellingCompanyCode(String value) {
        this.sellingCompanyCode = value;
    }

    /**
     * Gets the value of the adultPortTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdultPortTax() {
        return adultPortTax;
    }

    /**
     * Sets the value of the adultPortTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdultPortTax(BigDecimal value) {
        this.adultPortTax = value;
    }

    /**
     * Gets the value of the airPriceIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAirPriceIncluded() {
        return airPriceIncluded;
    }

    /**
     * Sets the value of the airPriceIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAirPriceIncluded(Boolean value) {
        this.airPriceIncluded = value;
    }

    /**
     * Gets the value of the childPortTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChildPortTax() {
        return childPortTax;
    }

    /**
     * Sets the value of the childPortTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChildPortTax(BigDecimal value) {
        this.childPortTax = value;
    }

    /**
     * Gets the value of the foodFundPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFoodFundPrice() {
        return foodFundPrice;
    }

    /**
     * Sets the value of the foodFundPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFoodFundPrice(BigDecimal value) {
        this.foodFundPrice = value;
    }

    /**
     * Gets the value of the priceIsIndicative property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPriceIsIndicative() {
        return priceIsIndicative;
    }

    /**
     * Sets the value of the priceIsIndicative property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPriceIsIndicative(Boolean value) {
        this.priceIsIndicative = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

}
