//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttsl.marketvariationdepartureinfo._2010._09._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketVariationDepartureInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketVariationDepartureInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarketVariationPricings" type="{http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1}ArrayOfMarketVariationPricing" minOccurs="0"/>
 *         &lt;element name="Departures" type="{http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1}ArrayOfDeparture" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BrochureCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MarketVariationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MarketVariationId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="OperatingProductCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OperatingProductId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="BookableOnline" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="TourPackage" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketVariationDepartureInfo", propOrder = {
    "marketVariationPricings",
    "departures"
})
public class MarketVariationDepartureInfo {

    @XmlElement(name = "MarketVariationPricings")
    protected ArrayOfMarketVariationPricing marketVariationPricings;
    @XmlElementRef(name = "Departures", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", type = JAXBElement.class)
    protected JAXBElement<ArrayOfDeparture> departures;
    @XmlAttribute(name = "BrochureCode")
    protected String brochureCode;
    @XmlAttribute(name = "MarketVariationCode")
    protected String marketVariationCode;
    @XmlAttribute(name = "MarketVariationId")
    protected Long marketVariationId;
    @XmlAttribute(name = "OperatingProductCode")
    protected String operatingProductCode;
    @XmlAttribute(name = "OperatingProductId")
    protected Long operatingProductId;
    @XmlAttribute(name = "BookableOnline")
    protected Boolean bookableOnline;
    @XmlAttribute(name = "TourPackage")
    protected Boolean tourPackage;

    /**
     * Gets the value of the marketVariationPricings property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMarketVariationPricing }
     *     
     */
    public ArrayOfMarketVariationPricing getMarketVariationPricings() {
        return marketVariationPricings;
    }

    /**
     * Sets the value of the marketVariationPricings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMarketVariationPricing }
     *     
     */
    public void setMarketVariationPricings(ArrayOfMarketVariationPricing value) {
        this.marketVariationPricings = value;
    }

    /**
     * Gets the value of the departures property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfDeparture }{@code >}
     *     
     */
    public JAXBElement<ArrayOfDeparture> getDepartures() {
        return departures;
    }

    /**
     * Sets the value of the departures property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfDeparture }{@code >}
     *     
     */
    public void setDepartures(JAXBElement<ArrayOfDeparture> value) {
        this.departures = ((JAXBElement<ArrayOfDeparture> ) value);
    }

    /**
     * Gets the value of the brochureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrochureCode() {
        return brochureCode;
    }

    /**
     * Sets the value of the brochureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrochureCode(String value) {
        this.brochureCode = value;
    }

    /**
     * Gets the value of the marketVariationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketVariationCode() {
        return marketVariationCode;
    }

    /**
     * Sets the value of the marketVariationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketVariationCode(String value) {
        this.marketVariationCode = value;
    }

    /**
     * Gets the value of the marketVariationId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMarketVariationId() {
        return marketVariationId;
    }

    /**
     * Sets the value of the marketVariationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMarketVariationId(Long value) {
        this.marketVariationId = value;
    }

    /**
     * Gets the value of the operatingProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingProductCode() {
        return operatingProductCode;
    }

    /**
     * Sets the value of the operatingProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingProductCode(String value) {
        this.operatingProductCode = value;
    }

    /**
     * Gets the value of the operatingProductId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOperatingProductId() {
        return operatingProductId;
    }

    /**
     * Sets the value of the operatingProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOperatingProductId(Long value) {
        this.operatingProductId = value;
    }

    /**
     * Gets the value of the bookableOnline property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBookableOnline() {
        return bookableOnline;
    }

    /**
     * Sets the value of the bookableOnline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBookableOnline(Boolean value) {
        this.bookableOnline = value;
    }

    /**
     * Gets the value of the tourPackage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTourPackage() {
        return tourPackage;
    }

    /**
     * Sets the value of the tourPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTourPackage(Boolean value) {
        this.tourPackage = value;
    }

}
