//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttsl.marketvariationdepartureinfo._2010._09._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ttsl.marketvariationdepartureinfo._2010._09._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MarketVariationDepartureInfo_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "MarketVariationDepartureInfo");
    private final static QName _MarketVariationDepartureInfoDepartures_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "Departures");
    private final static QName _DeparturePricingMandatoryProducts_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "MandatoryProducts");
    private final static QName _DeparturePricingSurcharges_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "Surcharges");
    private final static QName _AssociatedInsuranceProductDescription_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "ProductDescription");
    private final static QName _AssociatedInsuranceProductName_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "ProductName");
    private final static QName _AssociatedInsuranceCurrencyCode_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "CurrencyCode");
    private final static QName _AssociatedInsuranceCode_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "Code");
    private final static QName _CommentsForDepartureCommentText_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "CommentText");
    private final static QName _BrochureShortDescription_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "ShortDescription");
    private final static QName _BrochureBrochureName_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "BrochureName");
    private final static QName _BrochureBrochureCode_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "BrochureCode");
    private final static QName _BrochureLongDescription_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "LongDescription");
    private final static QName _BrochureBrandCode_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "BrandCode");
    private final static QName _BrochureBrochureYear_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "BrochureYear");
    private final static QName _BrochureSellingCompanyCode_QNAME = new QName("http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", "SellingCompanyCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ttsl.marketvariationdepartureinfo._2010._09._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeparturePricing }
     * 
     */
    public DeparturePricing createDeparturePricing() {
        return new DeparturePricing();
    }

    /**
     * Create an instance of {@link Surcharge }
     * 
     */
    public Surcharge createSurcharge() {
        return new Surcharge();
    }

    /**
     * Create an instance of {@link Departure }
     * 
     */
    public Departure createDeparture() {
        return new Departure();
    }

    /**
     * Create an instance of {@link AssociatedInsurance }
     * 
     */
    public AssociatedInsurance createAssociatedInsurance() {
        return new AssociatedInsurance();
    }

    /**
     * Create an instance of {@link ArrayOfMarketVariationPricing }
     * 
     */
    public ArrayOfMarketVariationPricing createArrayOfMarketVariationPricing() {
        return new ArrayOfMarketVariationPricing();
    }

    /**
     * Create an instance of {@link ArrayOfDeparturePricing }
     * 
     */
    public ArrayOfDeparturePricing createArrayOfDeparturePricing() {
        return new ArrayOfDeparturePricing();
    }

    /**
     * Create an instance of {@link MarketVariationDepartureInfo }
     * 
     */
    public MarketVariationDepartureInfo createMarketVariationDepartureInfo() {
        return new MarketVariationDepartureInfo();
    }

    /**
     * Create an instance of {@link ArrayOfDeparture }
     * 
     */
    public ArrayOfDeparture createArrayOfDeparture() {
        return new ArrayOfDeparture();
    }

    /**
     * Create an instance of {@link MandatoryProduct }
     * 
     */
    public MandatoryProduct createMandatoryProduct() {
        return new MandatoryProduct();
    }

    /**
     * Create an instance of {@link CommentsForDeparture }
     * 
     */
    public CommentsForDeparture createCommentsForDeparture() {
        return new CommentsForDeparture();
    }

    /**
     * Create an instance of {@link MarketVariationPricing }
     * 
     */
    public MarketVariationPricing createMarketVariationPricing() {
        return new MarketVariationPricing();
    }

    /**
     * Create an instance of {@link ArrayOfSurcharge }
     * 
     */
    public ArrayOfSurcharge createArrayOfSurcharge() {
        return new ArrayOfSurcharge();
    }

    /**
     * Create an instance of {@link Brochure }
     * 
     */
    public Brochure createBrochure() {
        return new Brochure();
    }

    /**
     * Create an instance of {@link ArrayOfMandatoryProduct }
     * 
     */
    public ArrayOfMandatoryProduct createArrayOfMandatoryProduct() {
        return new ArrayOfMandatoryProduct();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarketVariationDepartureInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "MarketVariationDepartureInfo")
    public JAXBElement<MarketVariationDepartureInfo> createMarketVariationDepartureInfo(MarketVariationDepartureInfo value) {
        return new JAXBElement<MarketVariationDepartureInfo>(_MarketVariationDepartureInfo_QNAME, MarketVariationDepartureInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfDeparture }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "Departures", scope = MarketVariationDepartureInfo.class)
    public JAXBElement<ArrayOfDeparture> createMarketVariationDepartureInfoDepartures(ArrayOfDeparture value) {
        return new JAXBElement<ArrayOfDeparture>(_MarketVariationDepartureInfoDepartures_QNAME, ArrayOfDeparture.class, MarketVariationDepartureInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfMandatoryProduct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "MandatoryProducts", scope = DeparturePricing.class)
    public JAXBElement<ArrayOfMandatoryProduct> createDeparturePricingMandatoryProducts(ArrayOfMandatoryProduct value) {
        return new JAXBElement<ArrayOfMandatoryProduct>(_DeparturePricingMandatoryProducts_QNAME, ArrayOfMandatoryProduct.class, DeparturePricing.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfSurcharge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "Surcharges", scope = DeparturePricing.class)
    public JAXBElement<ArrayOfSurcharge> createDeparturePricingSurcharges(ArrayOfSurcharge value) {
        return new JAXBElement<ArrayOfSurcharge>(_DeparturePricingSurcharges_QNAME, ArrayOfSurcharge.class, DeparturePricing.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "ProductDescription", scope = AssociatedInsurance.class)
    public JAXBElement<String> createAssociatedInsuranceProductDescription(String value) {
        return new JAXBElement<String>(_AssociatedInsuranceProductDescription_QNAME, String.class, AssociatedInsurance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "ProductName", scope = AssociatedInsurance.class)
    public JAXBElement<String> createAssociatedInsuranceProductName(String value) {
        return new JAXBElement<String>(_AssociatedInsuranceProductName_QNAME, String.class, AssociatedInsurance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "CurrencyCode", scope = AssociatedInsurance.class)
    public JAXBElement<String> createAssociatedInsuranceCurrencyCode(String value) {
        return new JAXBElement<String>(_AssociatedInsuranceCurrencyCode_QNAME, String.class, AssociatedInsurance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "Code", scope = AssociatedInsurance.class)
    public JAXBElement<String> createAssociatedInsuranceCode(String value) {
        return new JAXBElement<String>(_AssociatedInsuranceCode_QNAME, String.class, AssociatedInsurance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "CommentText", scope = CommentsForDeparture.class)
    public JAXBElement<String> createCommentsForDepartureCommentText(String value) {
        return new JAXBElement<String>(_CommentsForDepartureCommentText_QNAME, String.class, CommentsForDeparture.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "ShortDescription", scope = Brochure.class)
    public JAXBElement<String> createBrochureShortDescription(String value) {
        return new JAXBElement<String>(_BrochureShortDescription_QNAME, String.class, Brochure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "BrochureName", scope = Brochure.class)
    public JAXBElement<String> createBrochureBrochureName(String value) {
        return new JAXBElement<String>(_BrochureBrochureName_QNAME, String.class, Brochure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "BrochureCode", scope = Brochure.class)
    public JAXBElement<String> createBrochureBrochureCode(String value) {
        return new JAXBElement<String>(_BrochureBrochureCode_QNAME, String.class, Brochure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "LongDescription", scope = Brochure.class)
    public JAXBElement<String> createBrochureLongDescription(String value) {
        return new JAXBElement<String>(_BrochureLongDescription_QNAME, String.class, Brochure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "BrandCode", scope = Brochure.class)
    public JAXBElement<String> createBrochureBrandCode(String value) {
        return new JAXBElement<String>(_BrochureBrandCode_QNAME, String.class, Brochure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "BrochureYear", scope = Brochure.class)
    public JAXBElement<String> createBrochureBrochureYear(String value) {
        return new JAXBElement<String>(_BrochureBrochureYear_QNAME, String.class, Brochure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", name = "SellingCompanyCode", scope = Brochure.class)
    public JAXBElement<String> createBrochureSellingCompanyCode(String value) {
        return new JAXBElement<String>(_BrochureSellingCompanyCode_QNAME, String.class, Brochure.class, value);
    }

}
