//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.tourdeparturessimp._2014._04._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccommodationProductTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccommodationProductTypeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PreAccommodation"/>
 *     &lt;enumeration value="PostAccommodation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AccommodationProductTypeCodeType")
@XmlEnum
public enum AccommodationProductTypeCodeType {

    @XmlEnumValue("PreAccommodation")
    PRE_ACCOMMODATION("PreAccommodation"),
    @XmlEnumValue("PostAccommodation")
    POST_ACCOMMODATION("PostAccommodation");
    private final String value;

    AccommodationProductTypeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccommodationProductTypeCodeType fromValue(String v) {
        for (AccommodationProductTypeCodeType c: AccommodationProductTypeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
