//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.tourdeparturessimp._2014._04._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssociatedProductsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedProductsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccommodationProducts" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}AccommodationProductsType" minOccurs="0"/>
 *         &lt;element name="MiscellaneousProducts" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}MiscellaneousProductsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedProductsType", propOrder = {
    "accommodationProducts",
    "miscellaneousProducts"
})
public class AssociatedProductsType {

    @XmlElement(name = "AccommodationProducts")
    protected AccommodationProductsType accommodationProducts;
    @XmlElement(name = "MiscellaneousProducts")
    protected MiscellaneousProductsType miscellaneousProducts;

    /**
     * Gets the value of the accommodationProducts property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationProductsType }
     *     
     */
    public AccommodationProductsType getAccommodationProducts() {
        return accommodationProducts;
    }

    /**
     * Sets the value of the accommodationProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationProductsType }
     *     
     */
    public void setAccommodationProducts(AccommodationProductsType value) {
        this.accommodationProducts = value;
    }

    /**
     * Gets the value of the miscellaneousProducts property.
     * 
     * @return
     *     possible object is
     *     {@link MiscellaneousProductsType }
     *     
     */
    public MiscellaneousProductsType getMiscellaneousProducts() {
        return miscellaneousProducts;
    }

    /**
     * Sets the value of the miscellaneousProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscellaneousProductsType }
     *     
     */
    public void setMiscellaneousProducts(MiscellaneousProductsType value) {
        this.miscellaneousProducts = value;
    }

}
