//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.tourdeparturessimp._2014._04._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeparturesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeparturesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Departure" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}DepartureType" maxOccurs="unbounded"/>
 *         &lt;element name="PricesRange" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PricesRangeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeparturesType", propOrder = {
    "departure",
    "pricesRange"
})
public class DeparturesType {

    @XmlElement(name = "Departure", required = true)
    protected List<DepartureType> departure;
    @XmlElement(name = "PricesRange", required = true)
    protected PricesRangeType pricesRange;

    /**
     * Gets the value of the departure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the departure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeparture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DepartureType }
     * 
     * 
     */
    public List<DepartureType> getDeparture() {
        if (departure == null) {
            departure = new ArrayList<DepartureType>();
        }
        return this.departure;
    }

    /**
     * Gets the value of the pricesRange property.
     * 
     * @return
     *     possible object is
     *     {@link PricesRangeType }
     *     
     */
    public PricesRangeType getPricesRange() {
        return pricesRange;
    }

    /**
     * Sets the value of the pricesRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricesRangeType }
     *     
     */
    public void setPricesRange(PricesRangeType value) {
        this.pricesRange = value;
    }

}
