//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.tourdeparturessimp._2014._04._3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ttc.ch2.schema.tourdeparturessimp._2014._04._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TourDeparturesSimp_QNAME = new QName("http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0", "TourDeparturesSimp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ttc.ch2.schema.tourdeparturessimp._2014._04._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoomPriceType }
     * 
     */
    public RoomPriceType createRoomPriceType() {
        return new RoomPriceType();
    }

    /**
     * Create an instance of {@link TourDeparturesSimpType }
     * 
     */
    public TourDeparturesSimpType createTourDeparturesSimpType() {
        return new TourDeparturesSimpType();
    }

    /**
     * Create an instance of {@link PriceRangeType }
     * 
     */
    public PriceRangeType createPriceRangeType() {
        return new PriceRangeType();
    }

    /**
     * Create an instance of {@link AccommodationProductsType }
     * 
     */
    public AccommodationProductsType createAccommodationProductsType() {
        return new AccommodationProductsType();
    }

    /**
     * Create an instance of {@link SurchargeType }
     * 
     */
    public SurchargeType createSurchargeType() {
        return new SurchargeType();
    }

    /**
     * Create an instance of {@link DepartureType }
     * 
     */
    public DepartureType createDepartureType() {
        return new DepartureType();
    }

    /**
     * Create an instance of {@link PortTaxType }
     * 
     */
    public PortTaxType createPortTaxType() {
        return new PortTaxType();
    }

    /**
     * Create an instance of {@link CombinedIncludedChargesType }
     * 
     */
    public CombinedIncludedChargesType createCombinedIncludedChargesType() {
        return new CombinedIncludedChargesType();
    }

    /**
     * Create an instance of {@link ProductRoomType }
     * 
     */
    public ProductRoomType createProductRoomType() {
        return new ProductRoomType();
    }

    /**
     * Create an instance of {@link SurchargesType }
     * 
     */
    public SurchargesType createSurchargesType() {
        return new SurchargesType();
    }

    /**
     * Create an instance of {@link RoomsType }
     * 
     */
    public RoomsType createRoomsType() {
        return new RoomsType();
    }

    /**
     * Create an instance of {@link SellingCompanyType }
     * 
     */
    public SellingCompanyType createSellingCompanyType() {
        return new SellingCompanyType();
    }

    /**
     * Create an instance of {@link PassengerType }
     * 
     */
    public PassengerType createPassengerType() {
        return new PassengerType();
    }

    /**
     * Create an instance of {@link RoomType }
     * 
     */
    public RoomType createRoomType() {
        return new RoomType();
    }

    /**
     * Create an instance of {@link TourRulesType }
     * 
     */
    public TourRulesType createTourRulesType() {
        return new TourRulesType();
    }

    /**
     * Create an instance of {@link PassengersType }
     * 
     */
    public PassengersType createPassengersType() {
        return new PassengersType();
    }

    /**
     * Create an instance of {@link FoodFundType }
     * 
     */
    public FoodFundType createFoodFundType() {
        return new FoodFundType();
    }

    /**
     * Create an instance of {@link PricesRangeType }
     * 
     */
    public PricesRangeType createPricesRangeType() {
        return new PricesRangeType();
    }

    /**
     * Create an instance of {@link OccupancyRuleType }
     * 
     */
    public OccupancyRuleType createOccupancyRuleType() {
        return new OccupancyRuleType();
    }

    /**
     * Create an instance of {@link AccommodationProductType }
     * 
     */
    public AccommodationProductType createAccommodationProductType() {
        return new AccommodationProductType();
    }

    /**
     * Create an instance of {@link MandatoryMiscellaneousProductsType }
     * 
     */
    public MandatoryMiscellaneousProductsType createMandatoryMiscellaneousProductsType() {
        return new MandatoryMiscellaneousProductsType();
    }

    /**
     * Create an instance of {@link DeparturesType }
     * 
     */
    public DeparturesType createDeparturesType() {
        return new DeparturesType();
    }

    /**
     * Create an instance of {@link MiscellaneousProductType }
     * 
     */
    public MiscellaneousProductType createMiscellaneousProductType() {
        return new MiscellaneousProductType();
    }

    /**
     * Create an instance of {@link PriceType }
     * 
     */
    public PriceType createPriceType() {
        return new PriceType();
    }

    /**
     * Create an instance of {@link ProductRoomsType }
     * 
     */
    public ProductRoomsType createProductRoomsType() {
        return new ProductRoomsType();
    }

    /**
     * Create an instance of {@link DiscountsType }
     * 
     */
    public DiscountsType createDiscountsType() {
        return new DiscountsType();
    }

    /**
     * Create an instance of {@link AssociatedProductsType }
     * 
     */
    public AssociatedProductsType createAssociatedProductsType() {
        return new AssociatedProductsType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link MiscellaneousProductsType }
     * 
     */
    public MiscellaneousProductsType createMiscellaneousProductsType() {
        return new MiscellaneousProductsType();
    }

    /**
     * Create an instance of {@link DiscountType }
     * 
     */
    public DiscountType createDiscountType() {
        return new DiscountType();
    }

    /**
     * Create an instance of {@link RoomPriceType.Adult }
     * 
     */
    public RoomPriceType.Adult createRoomPriceTypeAdult() {
        return new RoomPriceType.Adult();
    }

    /**
     * Create an instance of {@link RoomPriceType.Child }
     * 
     */
    public RoomPriceType.Child createRoomPriceTypeChild() {
        return new RoomPriceType.Child();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TourDeparturesSimpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0", name = "TourDeparturesSimp")
    public JAXBElement<TourDeparturesSimpType> createTourDeparturesSimp(TourDeparturesSimpType value) {
        return new JAXBElement<TourDeparturesSimpType>(_TourDeparturesSimp_QNAME, TourDeparturesSimpType.class, null, value);
    }

}
