//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ttc.ch2.schema.tourdeparturessimp._2014._04._3;
