//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.tourdeparturessimp._2014._04._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PricesRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricesRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SingleRoom" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PriceRangeType"/>
 *         &lt;element name="TwinRoom" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PriceRangeType"/>
 *         &lt;element name="TwinShareRoom" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PriceRangeType"/>
 *         &lt;element name="TripleRoom" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PriceRangeType"/>
 *         &lt;element name="TripleShareRoom" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PriceRangeType"/>
 *         &lt;element name="QuadRoom" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PriceRangeType"/>
 *         &lt;element name="QuadShareRoom" type="{http://schema.ch2.ttc.com/TourDeparturesSimp/2014/04/3.0}PriceRangeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricesRangeType", propOrder = {
    "singleRoom",
    "twinRoom",
    "twinShareRoom",
    "tripleRoom",
    "tripleShareRoom",
    "quadRoom",
    "quadShareRoom"
})
public class PricesRangeType {

    @XmlElement(name = "SingleRoom", required = true)
    protected PriceRangeType singleRoom;
    @XmlElement(name = "TwinRoom", required = true)
    protected PriceRangeType twinRoom;
    @XmlElement(name = "TwinShareRoom", required = true)
    protected PriceRangeType twinShareRoom;
    @XmlElement(name = "TripleRoom", required = true)
    protected PriceRangeType tripleRoom;
    @XmlElement(name = "TripleShareRoom", required = true)
    protected PriceRangeType tripleShareRoom;
    @XmlElement(name = "QuadRoom", required = true)
    protected PriceRangeType quadRoom;
    @XmlElement(name = "QuadShareRoom", required = true)
    protected PriceRangeType quadShareRoom;

    /**
     * Gets the value of the singleRoom property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRangeType }
     *     
     */
    public PriceRangeType getSingleRoom() {
        return singleRoom;
    }

    /**
     * Sets the value of the singleRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRangeType }
     *     
     */
    public void setSingleRoom(PriceRangeType value) {
        this.singleRoom = value;
    }

    /**
     * Gets the value of the twinRoom property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRangeType }
     *     
     */
    public PriceRangeType getTwinRoom() {
        return twinRoom;
    }

    /**
     * Sets the value of the twinRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRangeType }
     *     
     */
    public void setTwinRoom(PriceRangeType value) {
        this.twinRoom = value;
    }

    /**
     * Gets the value of the twinShareRoom property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRangeType }
     *     
     */
    public PriceRangeType getTwinShareRoom() {
        return twinShareRoom;
    }

    /**
     * Sets the value of the twinShareRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRangeType }
     *     
     */
    public void setTwinShareRoom(PriceRangeType value) {
        this.twinShareRoom = value;
    }

    /**
     * Gets the value of the tripleRoom property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRangeType }
     *     
     */
    public PriceRangeType getTripleRoom() {
        return tripleRoom;
    }

    /**
     * Sets the value of the tripleRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRangeType }
     *     
     */
    public void setTripleRoom(PriceRangeType value) {
        this.tripleRoom = value;
    }

    /**
     * Gets the value of the tripleShareRoom property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRangeType }
     *     
     */
    public PriceRangeType getTripleShareRoom() {
        return tripleShareRoom;
    }

    /**
     * Sets the value of the tripleShareRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRangeType }
     *     
     */
    public void setTripleShareRoom(PriceRangeType value) {
        this.tripleShareRoom = value;
    }

    /**
     * Gets the value of the quadRoom property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRangeType }
     *     
     */
    public PriceRangeType getQuadRoom() {
        return quadRoom;
    }

    /**
     * Sets the value of the quadRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRangeType }
     *     
     */
    public void setQuadRoom(PriceRangeType value) {
        this.quadRoom = value;
    }

    /**
     * Gets the value of the quadShareRoom property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRangeType }
     *     
     */
    public PriceRangeType getQuadShareRoom() {
        return quadShareRoom;
    }

    /**
     * Sets the value of the quadShareRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRangeType }
     *     
     */
    public void setQuadShareRoom(PriceRangeType value) {
        this.quadShareRoom = value;
    }

}
