//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.tourdeparturessimp._2014._04._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoomTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoomTypeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Single"/>
 *     &lt;enumeration value="Twin"/>
 *     &lt;enumeration value="TwinShare"/>
 *     &lt;enumeration value="Triple"/>
 *     &lt;enumeration value="TripleShare"/>
 *     &lt;enumeration value="Quad"/>
 *     &lt;enumeration value="QuadShare"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoomTypeCodeType")
@XmlEnum
public enum RoomTypeCodeType {

    @XmlEnumValue("Single")
    SINGLE("Single"),
    @XmlEnumValue("Twin")
    TWIN("Twin"),
    @XmlEnumValue("TwinShare")
    TWIN_SHARE("TwinShare"),
    @XmlEnumValue("Triple")
    TRIPLE("Triple"),
    @XmlEnumValue("TripleShare")
    TRIPLE_SHARE("TripleShare"),
    @XmlEnumValue("Quad")
    QUAD("Quad"),
    @XmlEnumValue("QuadShare")
    QUAD_SHARE("QuadShare");
    private final String value;

    RoomTypeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoomTypeCodeType fromValue(String v) {
        for (RoomTypeCodeType c: RoomTypeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
