//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 12:21:35 PM CEST 
//


package com.ttc.ch2.schema.tourinfosimp._2014._01._3;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ttc.ch2.schema.tourinfosimp._2014._01._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ttc.ch2.schema.tourinfosimp._2014._01._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TourInfoSimp }
     * 
     */
    public TourInfoSimp createTourInfoSimp() {
        return new TourInfoSimp();
    }

    /**
     * Create an instance of {@link CataloguedTour }
     * 
     */
    public CataloguedTour createCataloguedTour() {
        return new CataloguedTour();
    }

    /**
     * Create an instance of {@link SellingCompanies }
     * 
     */
    public SellingCompanies createSellingCompanies() {
        return new SellingCompanies();
    }

    /**
     * Create an instance of {@link TourVariationDefiners }
     * 
     */
    public TourVariationDefiners createTourVariationDefiners() {
        return new TourVariationDefiners();
    }

    /**
     * Create an instance of {@link ContinentsVisited }
     * 
     */
    public ContinentsVisited createContinentsVisited() {
        return new ContinentsVisited();
    }

    /**
     * Create an instance of {@link CountriesVisited }
     * 
     */
    public CountriesVisited createCountriesVisited() {
        return new CountriesVisited();
    }

    /**
     * Create an instance of {@link LocationsVisited }
     * 
     */
    public LocationsVisited createLocationsVisited() {
        return new LocationsVisited();
    }

    /**
     * Create an instance of {@link Assets }
     * 
     */
    public Assets createAssets() {
        return new Assets();
    }

    /**
     * Create an instance of {@link Itinerary }
     * 
     */
    public Itinerary createItinerary() {
        return new Itinerary();
    }

    /**
     * Create an instance of {@link WhatsIncluded }
     * 
     */
    public WhatsIncluded createWhatsIncluded() {
        return new WhatsIncluded();
    }

    /**
     * Create an instance of {@link Highlights }
     * 
     */
    public Highlights createHighlights() {
        return new Highlights();
    }

    /**
     * Create an instance of {@link AirportTransfers }
     * 
     */
    public AirportTransfers createAirportTransfers() {
        return new AirportTransfers();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link AdditionalInfo }
     * 
     */
    public AdditionalInfo createAdditionalInfo() {
        return new AdditionalInfo();
    }

    /**
     * Create an instance of {@link KeywordsPhrases }
     * 
     */
    public KeywordsPhrases createKeywordsPhrases() {
        return new KeywordsPhrases();
    }

    /**
     * Create an instance of {@link OperatingProduct }
     * 
     */
    public OperatingProduct createOperatingProduct() {
        return new OperatingProduct();
    }

    /**
     * Create an instance of {@link Extra }
     * 
     */
    public Extra createExtra() {
        return new Extra();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link OptionalExtras }
     * 
     */
    public OptionalExtras createOptionalExtras() {
        return new OptionalExtras();
    }

    /**
     * Create an instance of {@link ItinerarySegment }
     * 
     */
    public ItinerarySegment createItinerarySegment() {
        return new ItinerarySegment();
    }

    /**
     * Create an instance of {@link MarketingFlags }
     * 
     */
    public MarketingFlags createMarketingFlags() {
        return new MarketingFlags();
    }

    /**
     * Create an instance of {@link TourCategory }
     * 
     */
    public TourCategory createTourCategory() {
        return new TourCategory();
    }

    /**
     * Create an instance of {@link RoomType }
     * 
     */
    public RoomType createRoomType() {
        return new RoomType();
    }

    /**
     * Create an instance of {@link Videos }
     * 
     */
    public Videos createVideos() {
        return new Videos();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Continent }
     * 
     */
    public Continent createContinent() {
        return new Continent();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link IncludedSubProduct }
     * 
     */
    public IncludedSubProduct createIncludedSubProduct() {
        return new IncludedSubProduct();
    }

    /**
     * Create an instance of {@link Airports }
     * 
     */
    public Airports createAirports() {
        return new Airports();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Meals }
     * 
     */
    public Meals createMeals() {
        return new Meals();
    }

    /**
     * Create an instance of {@link SellingCompany }
     * 
     */
    public SellingCompany createSellingCompany() {
        return new SellingCompany();
    }

    /**
     * Create an instance of {@link AdditionalDefiners }
     * 
     */
    public AdditionalDefiners createAdditionalDefiners() {
        return new AdditionalDefiners();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link RoomTypes }
     * 
     */
    public RoomTypes createRoomTypes() {
        return new RoomTypes();
    }

    /**
     * Create an instance of {@link Meal }
     * 
     */
    public Meal createMeal() {
        return new Meal();
    }

    /**
     * Create an instance of {@link IncludedSubProducts }
     * 
     */
    public IncludedSubProducts createIncludedSubProducts() {
        return new IncludedSubProducts();
    }

    /**
     * Create an instance of {@link TourCategories }
     * 
     */
    public TourCategories createTourCategories() {
        return new TourCategories();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link Brochure }
     * 
     */
    public Brochure createBrochure() {
        return new Brochure();
    }

}
