//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.01 at 03:43:32 PM CEST 
//


package com.ttc.ch2.api.ccapi.v3.tourinfo._2014._01._3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ttc.ch2.api.ccapi.v3.tourinfo._2014._01._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LiA_QNAME = new QName("http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", "a");
    private final static QName _LiStrong_QNAME = new QName("http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", "strong");
    private final static QName _LiValues_QNAME = new QName("http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", "values");
    private final static QName _TextUl_QNAME = new QName("http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", "ul");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ttc.ch2.api.ccapi.v3.tourinfo._2014._01._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TourInfo }
     * 
     */
    public TourInfo createTourInfo() {
        return new TourInfo();
    }

    /**
     * Create an instance of {@link CataloguedTour }
     * 
     */
    public CataloguedTour createCataloguedTour() {
        return new CataloguedTour();
    }

    /**
     * Create an instance of {@link SellingCompanies }
     * 
     */
    public SellingCompanies createSellingCompanies() {
        return new SellingCompanies();
    }

    /**
     * Create an instance of {@link TourVariationDefiners }
     * 
     */
    public TourVariationDefiners createTourVariationDefiners() {
        return new TourVariationDefiners();
    }

    /**
     * Create an instance of {@link ContinentsVisited }
     * 
     */
    public ContinentsVisited createContinentsVisited() {
        return new ContinentsVisited();
    }

    /**
     * Create an instance of {@link CountriesVisited }
     * 
     */
    public CountriesVisited createCountriesVisited() {
        return new CountriesVisited();
    }

    /**
     * Create an instance of {@link LocationsVisited }
     * 
     */
    public LocationsVisited createLocationsVisited() {
        return new LocationsVisited();
    }

    /**
     * Create an instance of {@link Assets }
     * 
     */
    public Assets createAssets() {
        return new Assets();
    }

    /**
     * Create an instance of {@link Itinerary }
     * 
     */
    public Itinerary createItinerary() {
        return new Itinerary();
    }

    /**
     * Create an instance of {@link WhatsIncluded }
     * 
     */
    public WhatsIncluded createWhatsIncluded() {
        return new WhatsIncluded();
    }

    /**
     * Create an instance of {@link Highlights }
     * 
     */
    public Highlights createHighlights() {
        return new Highlights();
    }

    /**
     * Create an instance of {@link AirportTransfers }
     * 
     */
    public AirportTransfers createAirportTransfers() {
        return new AirportTransfers();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link AdditionalInfo }
     * 
     */
    public AdditionalInfo createAdditionalInfo() {
        return new AdditionalInfo();
    }

    /**
     * Create an instance of {@link Br }
     * 
     */
    public Br createBr() {
        return new Br();
    }

    /**
     * Create an instance of {@link TourCategories }
     * 
     */
    public TourCategories createTourCategories() {
        return new TourCategories();
    }

    /**
     * Create an instance of {@link MarketingFlags }
     * 
     */
    public MarketingFlags createMarketingFlags() {
        return new MarketingFlags();
    }

    /**
     * Create an instance of {@link RoomTypes }
     * 
     */
    public RoomTypes createRoomTypes() {
        return new RoomTypes();
    }

    /**
     * Create an instance of {@link ItinerarySegment }
     * 
     */
    public ItinerarySegment createItinerarySegment() {
        return new ItinerarySegment();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link IncludedSubProduct }
     * 
     */
    public IncludedSubProduct createIncludedSubProduct() {
        return new IncludedSubProduct();
    }

    /**
     * Create an instance of {@link Ul }
     * 
     */
    public Ul createUl() {
        return new Ul();
    }

    /**
     * Create an instance of {@link Meals }
     * 
     */
    public Meals createMeals() {
        return new Meals();
    }

    /**
     * Create an instance of {@link IncludedSubProducts }
     * 
     */
    public IncludedSubProducts createIncludedSubProducts() {
        return new IncludedSubProducts();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link Airports }
     * 
     */
    public Airports createAirports() {
        return new Airports();
    }

    /**
     * Create an instance of {@link SellingCompany }
     * 
     */
    public SellingCompany createSellingCompany() {
        return new SellingCompany();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link OperatingProduct }
     * 
     */
    public OperatingProduct createOperatingProduct() {
        return new OperatingProduct();
    }

    /**
     * Create an instance of {@link Strong }
     * 
     */
    public Strong createStrong() {
        return new Strong();
    }

    /**
     * Create an instance of {@link Meal }
     * 
     */
    public Meal createMeal() {
        return new Meal();
    }

    /**
     * Create an instance of {@link TourCategory }
     * 
     */
    public TourCategory createTourCategory() {
        return new TourCategory();
    }

    /**
     * Create an instance of {@link Videos }
     * 
     */
    public Videos createVideos() {
        return new Videos();
    }

    /**
     * Create an instance of {@link OptionalExtras }
     * 
     */
    public OptionalExtras createOptionalExtras() {
        return new OptionalExtras();
    }

    /**
     * Create an instance of {@link RoomType }
     * 
     */
    public RoomType createRoomType() {
        return new RoomType();
    }

    /**
     * Create an instance of {@link KeywordsPhrases }
     * 
     */
    public KeywordsPhrases createKeywordsPhrases() {
        return new KeywordsPhrases();
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link Brochure }
     * 
     */
    public Brochure createBrochure() {
        return new Brochure();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link AdditionalDefiners }
     * 
     */
    public AdditionalDefiners createAdditionalDefiners() {
        return new AdditionalDefiners();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Continent }
     * 
     */
    public Continent createContinent() {
        return new Continent();
    }

    /**
     * Create an instance of {@link Extra }
     * 
     */
    public Extra createExtra() {
        return new Extra();
    }

    /**
     * Create an instance of {@link Li }
     * 
     */
    public Li createLi() {
        return new Li();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", name = "a", scope = Li.class)
    public JAXBElement<A> createLiA(A value) {
        return new JAXBElement<A>(_LiA_QNAME, A.class, Li.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", name = "strong", scope = Li.class)
    public JAXBElement<Strong> createLiStrong(Strong value) {
        return new JAXBElement<Strong>(_LiStrong_QNAME, Strong.class, Li.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", name = "values", scope = Li.class)
    public JAXBElement<String> createLiValues(String value) {
        return new JAXBElement<String>(_LiValues_QNAME, String.class, Li.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", name = "a", scope = Text.class)
    public JAXBElement<A> createTextA(A value) {
        return new JAXBElement<A>(_LiA_QNAME, A.class, Text.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", name = "strong", scope = Text.class)
    public JAXBElement<Strong> createTextStrong(Strong value) {
        return new JAXBElement<Strong>(_LiStrong_QNAME, Strong.class, Text.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", name = "values", scope = Text.class)
    public JAXBElement<String> createTextValues(String value) {
        return new JAXBElement<String>(_LiValues_QNAME, String.class, Text.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ul }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ttc.com/ch2/api/ccapi/v3/TourInfo/2014/01/3.0", name = "ul", scope = Text.class)
    public JAXBElement<Ul> createTextUl(Ul value) {
        return new JAXBElement<Ul>(_TextUl_QNAME, Ul.class, Text.class, value);
    }

}
