
package facade.itropics.webservice.tropics.com.itropicsbuildws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ITropicsBuild", targetNamespace = "http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", wsdlLocation = "http://londvap1.corp.ttc:7779/tropics/TropicsBuildWS?wsdl")
public class ITropicsBuild
    extends Service
{

    private final static URL ITROPICSBUILD_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(facade.itropics.webservice.tropics.com.itropicsbuildws.ITropicsBuild.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = facade.itropics.webservice.tropics.com.itropicsbuildws.ITropicsBuild.class.getResource(".");
            url = new URL(baseUrl, "http://londvap1.corp.ttc:7779/tropics/TropicsBuildWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://londvap1.corp.ttc:7779/tropics/TropicsBuildWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ITROPICSBUILD_WSDL_LOCATION = url;
    }

    public ITropicsBuild(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITropicsBuild() {
        super(ITROPICSBUILD_WSDL_LOCATION, new QName("http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", "ITropicsBuild"));
    }

    /**
     * 
     * @return
     *     returns ITropicsBuildWS
     */
    @WebEndpoint(name = "ITropicsBuildWSPort")
    public ITropicsBuildWS getITropicsBuildWSPort() {
        return super.getPort(new QName("http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", "ITropicsBuildWSPort"), ITropicsBuildWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITropicsBuildWS
     */
    @WebEndpoint(name = "ITropicsBuildWSPort")
    public ITropicsBuildWS getITropicsBuildWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", "ITropicsBuildWSPort"), ITropicsBuildWS.class, features);
    }

}
