
package com.wsout.habs.itropicsbuildws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ITropicsBuild", targetNamespace = "http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", wsdlLocation = "http://lonhabs01.corp.ttc:8883/prod-serv-web-TRUNK-SNAPSHOT/api/TropicsBuildWS?wsdl")
public class ITropicsBuild
    extends Service
{

    private final static URL ITROPICSBUILD_WSDL_LOCATION;
    private final static WebServiceException ITROPICSBUILD_EXCEPTION;
    private final static QName ITROPICSBUILD_QNAME = new QName("http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", "ITropicsBuild");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lonhabs01.corp.ttc:8883/prod-serv-web-TRUNK-SNAPSHOT/api/TropicsBuildWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITROPICSBUILD_WSDL_LOCATION = url;
        ITROPICSBUILD_EXCEPTION = e;
    }

    public ITropicsBuild() {
        super(__getWsdlLocation(), ITROPICSBUILD_QNAME);
    }

    public ITropicsBuild(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITROPICSBUILD_QNAME, features);
    }

    public ITropicsBuild(URL wsdlLocation) {
        super(wsdlLocation, ITROPICSBUILD_QNAME);
    }

    public ITropicsBuild(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITROPICSBUILD_QNAME, features);
    }

    public ITropicsBuild(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITropicsBuild(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITropicsBuildWS
     */
    @WebEndpoint(name = "ITropicsBuildWSPort")
    public ITropicsBuildWS getITropicsBuildWSPort() {
        return super.getPort(new QName("http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", "ITropicsBuildWSPort"), ITropicsBuildWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITropicsBuildWS
     */
    @WebEndpoint(name = "ITropicsBuildWSPort")
    public ITropicsBuildWS getITropicsBuildWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd", "ITropicsBuildWSPort"), ITropicsBuildWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITROPICSBUILD_EXCEPTION!= null) {
            throw ITROPICSBUILD_EXCEPTION;
        }
        return ITROPICSBUILD_WSDL_LOCATION;
    }

}
