
package com.wsout.habs.itropicsbuildws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITropicsBuildWS", targetNamespace = "http://com.tropics.webservice.iTropics.facade/ITropicsBuildWS.xsd")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITropicsBuildWS {


    /**
     * 
     * @param request
     * @return
     *     returns com.wsout.habs.itropicsbuildws.WsDeparturesVO
     */
    @WebMethod
    @WebResult(partName = "return")
    public WsDeparturesVO getTourDatesAndRates(
        @WebParam(name = "request", partName = "request")
        WsInGetTourDatesAndRatesVO request);

    /**
     * 
     * @param param
     * @return
     *     returns com.wsout.habs.itropicsbuildws.WsmVorTPDetailsVO
     */
    @WebMethod
    @WebResult(partName = "return")
    public WsmVorTPDetailsVO getMVorTPDetails(
        @WebParam(name = "param", partName = "param")
        WsInGetMvorTpDetails param);

    /**
     * 
     * @param request
     * @return
     *     returns com.wsout.habs.itropicsbuildws.ComTropicsWebserviceITropicsVoCurrentCommonWSGetAssociatedMiscProductsResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public ComTropicsWebserviceITropicsVoCurrentCommonWSGetAssociatedMiscProductsResponse getAssociatedMiscProducts(
        @WebParam(name = "request", partName = "request")
        ComTropicsWebserviceITropicsVoLegacyInputWSInGetAssociatedMiscProductsAPIVO request);

    /**
     * 
     * @param request
     * @return
     *     returns com.wsout.habs.itropicsbuildws.WsToursOfBrandsVO
     */
    @WebMethod
    @WebResult(partName = "return")
    public WsToursOfBrandsVO getToursOfBrands(
        @WebParam(name = "request", partName = "request")
        WsInGetToursOfBrandsVO request);

    /**
     * 
     * @param request
     * @return
     *     returns com.wsout.habs.itropicsbuildws.WsToursWithSCListVO
     */
    @WebMethod
    @WebResult(partName = "return")
    public WsToursWithSCListVO getToursWithSCList(
        @WebParam(name = "request", partName = "request")
        WsInGetToursWithSCListVO request);

}
