//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttc.ch2.api.ccapi.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.ttsl.marketvariationdepartureinfo._2010._09._1.MarketVariationDepartureInfo;
import com.ttsl.tourinfo._2010._08._2.TourInfo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}TourInfo"/>
 *         &lt;element ref="{http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1}MarketVariationDepartureInfo"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BrandCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SellingCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tourInfo",
    "marketVariationDepartureInfo"
})
@XmlRootElement(name = "TransformationSource")
public class TransformationSource {

    @XmlElement(name = "TourInfo", namespace = "http://www.ttsl.com/TourInfo/2010/08/2.4", required = true)
    protected TourInfo tourInfo;
    @XmlElement(name = "MarketVariationDepartureInfo", namespace = "http://www.ttsl.com/MarketVariationDepartureInfo/2010/09/1.1", required = true)
    protected MarketVariationDepartureInfo marketVariationDepartureInfo;
    @XmlAttribute(name = "BrandCode")
    protected String brandCode;
    @XmlAttribute(name = "SellingCompanyCode")
    protected String sellingCompanyCode;

    /**
     * Gets the value of the tourInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TourInfo }
     *     
     */
    public TourInfo getTourInfo() {
        return tourInfo;
    }

    /**
     * Sets the value of the tourInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TourInfo }
     *     
     */
    public void setTourInfo(TourInfo value) {
        this.tourInfo = value;
    }

    /**
     * Gets the value of the marketVariationDepartureInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MarketVariationDepartureInfo }
     *     
     */
    public MarketVariationDepartureInfo getMarketVariationDepartureInfo() {
        return marketVariationDepartureInfo;
    }

    /**
     * Sets the value of the marketVariationDepartureInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketVariationDepartureInfo }
     *     
     */
    public void setMarketVariationDepartureInfo(MarketVariationDepartureInfo value) {
        this.marketVariationDepartureInfo = value;
    }

    /**
     * Gets the value of the brandCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * Sets the value of the brandCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandCode(String value) {
        this.brandCode = value;
    }

    /**
     * Gets the value of the sellingCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellingCompanyCode() {
        return sellingCompanyCode;
    }

    /**
     * Sets the value of the sellingCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellingCompanyCode(String value) {
        this.sellingCompanyCode = value;
    }

}
