//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:04:24 PM CEST 
//


package com.travelcorp.ccapi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.travelcorp.ccapi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.travelcorp.ccapi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchTours }
     * 
     */
    public SearchTours createSearchTours() {
        return new SearchTours();
    }

    /**
     * Create an instance of {@link SearchToursResponse }
     * 
     */
    public SearchToursResponse createSearchToursResponse() {
        return new SearchToursResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link SearchTourResultsItem }
     * 
     */
    public SearchTourResultsItem createSearchTourResultsItem() {
        return new SearchTourResultsItem();
    }

    /**
     * Create an instance of {@link SearchTourResults }
     * 
     */
    public SearchTourResults createSearchTourResults() {
        return new SearchTourResults();
    }

    /**
     * Create an instance of {@link ArrayOfSearchTourResultsItem }
     * 
     */
    public ArrayOfSearchTourResultsItem createArrayOfSearchTourResultsItem() {
        return new ArrayOfSearchTourResultsItem();
    }

}
