//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:04:24 PM CEST 
//


package com.travelcorp.ccapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SearchToursResult" type="{http://CCAPI.TravelCorp.com/}SearchTourResults" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchToursResult"
})
@XmlRootElement(name = "SearchToursResponse")
public class SearchToursResponse {

    @XmlElement(name = "SearchToursResult")
    protected SearchTourResults searchToursResult;

    /**
     * Gets the value of the searchToursResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchTourResults }
     *     
     */
    public SearchTourResults getSearchToursResult() {
        return searchToursResult;
    }

    /**
     * Sets the value of the searchToursResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchTourResults }
     *     
     */
    public void setSearchToursResult(SearchTourResults value) {
        this.searchToursResult = value;
    }

}
