//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttsl.tourinfo._2010._08._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}TourCategories"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}SellingCompanies"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tourCategories",
    "sellingCompanies"
})
@XmlRootElement(name = "Metadata")
public class Metadata {

    @XmlElement(name = "TourCategories", required = true)
    protected TourCategories tourCategories;
    @XmlElement(name = "SellingCompanies", required = true)
    protected SellingCompanies sellingCompanies;

    /**
     * Gets the value of the tourCategories property.
     * 
     * @return
     *     possible object is
     *     {@link TourCategories }
     *     
     */
    public TourCategories getTourCategories() {
        return tourCategories;
    }

    /**
     * Sets the value of the tourCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link TourCategories }
     *     
     */
    public void setTourCategories(TourCategories value) {
        this.tourCategories = value;
    }

    /**
     * Gets the value of the sellingCompanies property.
     * 
     * @return
     *     possible object is
     *     {@link SellingCompanies }
     *     
     */
    public SellingCompanies getSellingCompanies() {
        return sellingCompanies;
    }

    /**
     * Sets the value of the sellingCompanies property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellingCompanies }
     *     
     */
    public void setSellingCompanies(SellingCompanies value) {
        this.sellingCompanies = value;
    }

}
