//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ttsl.com/TourInfo/2010/08/2.4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ttsl.tourinfo._2010._08._2;
