//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 04:01:34 PM CEST 
//


package com.ttsl.tourinfo._2010._08._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}TourName"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}Metadata"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}ContinentsVisited"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}CountriesVisited"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}LocationsVisited"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}Description"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}Assets"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}Itinerary"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}WhatsIncluded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}Highlights" minOccurs="0"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}AirportTransfers" minOccurs="0"/>
 *         &lt;element ref="{http://www.ttsl.com/TourInfo/2010/08/2.4}Notes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BrandCode" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="CMSId" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="CMSTourId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="CatalogueCode" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Duration" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="MVCode" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="OPCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tourName",
    "metadata",
    "continentsVisited",
    "countriesVisited",
    "locationsVisited",
    "description",
    "assets",
    "itinerary",
    "whatsIncluded",
    "highlights",
    "airportTransfers",
    "notes"
})
@XmlRootElement(name = "TourInfo")
public class TourInfo {

    @XmlElement(name = "TourName", required = true)
    protected String tourName;
    @XmlElement(name = "Metadata", required = true)
    protected Metadata metadata;
    @XmlElement(name = "ContinentsVisited", required = true)
    protected ContinentsVisited continentsVisited;
    @XmlElement(name = "CountriesVisited", required = true)
    protected CountriesVisited countriesVisited;
    @XmlElement(name = "LocationsVisited", required = true)
    protected LocationsVisited locationsVisited;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Assets", required = true)
    protected Assets assets;
    @XmlElement(name = "Itinerary", required = true)
    protected Itinerary itinerary;
    @XmlElement(name = "WhatsIncluded")
    protected WhatsIncluded whatsIncluded;
    @XmlElement(name = "Highlights")
    protected Highlights highlights;
    @XmlElement(name = "AirportTransfers")
    protected AirportTransfers airportTransfers;
    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlAttribute(name = "BrandCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String brandCode;
    @XmlAttribute(name = "CMSId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String cmsId;
    @XmlAttribute(name = "CMSTourId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String cmsTourId;
    @XmlAttribute(name = "CatalogueCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String catalogueCode;
    @XmlAttribute(name = "Duration", required = true)
    protected BigInteger duration;
    @XmlAttribute(name = "MVCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String mvCode;
    @XmlAttribute(name = "OPCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String opCode;

    /**
     * Gets the value of the tourName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTourName() {
        return tourName;
    }

    /**
     * Sets the value of the tourName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTourName(String value) {
        this.tourName = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the continentsVisited property.
     * 
     * @return
     *     possible object is
     *     {@link ContinentsVisited }
     *     
     */
    public ContinentsVisited getContinentsVisited() {
        return continentsVisited;
    }

    /**
     * Sets the value of the continentsVisited property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContinentsVisited }
     *     
     */
    public void setContinentsVisited(ContinentsVisited value) {
        this.continentsVisited = value;
    }

    /**
     * Gets the value of the countriesVisited property.
     * 
     * @return
     *     possible object is
     *     {@link CountriesVisited }
     *     
     */
    public CountriesVisited getCountriesVisited() {
        return countriesVisited;
    }

    /**
     * Sets the value of the countriesVisited property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountriesVisited }
     *     
     */
    public void setCountriesVisited(CountriesVisited value) {
        this.countriesVisited = value;
    }

    /**
     * Gets the value of the locationsVisited property.
     * 
     * @return
     *     possible object is
     *     {@link LocationsVisited }
     *     
     */
    public LocationsVisited getLocationsVisited() {
        return locationsVisited;
    }

    /**
     * Sets the value of the locationsVisited property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationsVisited }
     *     
     */
    public void setLocationsVisited(LocationsVisited value) {
        this.locationsVisited = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the assets property.
     * 
     * @return
     *     possible object is
     *     {@link Assets }
     *     
     */
    public Assets getAssets() {
        return assets;
    }

    /**
     * Sets the value of the assets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assets }
     *     
     */
    public void setAssets(Assets value) {
        this.assets = value;
    }

    /**
     * Gets the value of the itinerary property.
     * 
     * @return
     *     possible object is
     *     {@link Itinerary }
     *     
     */
    public Itinerary getItinerary() {
        return itinerary;
    }

    /**
     * Sets the value of the itinerary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Itinerary }
     *     
     */
    public void setItinerary(Itinerary value) {
        this.itinerary = value;
    }

    /**
     * Gets the value of the whatsIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link WhatsIncluded }
     *     
     */
    public WhatsIncluded getWhatsIncluded() {
        return whatsIncluded;
    }

    /**
     * Sets the value of the whatsIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhatsIncluded }
     *     
     */
    public void setWhatsIncluded(WhatsIncluded value) {
        this.whatsIncluded = value;
    }

    /**
     * Gets the value of the highlights property.
     * 
     * @return
     *     possible object is
     *     {@link Highlights }
     *     
     */
    public Highlights getHighlights() {
        return highlights;
    }

    /**
     * Sets the value of the highlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Highlights }
     *     
     */
    public void setHighlights(Highlights value) {
        this.highlights = value;
    }

    /**
     * Gets the value of the airportTransfers property.
     * 
     * @return
     *     possible object is
     *     {@link AirportTransfers }
     *     
     */
    public AirportTransfers getAirportTransfers() {
        return airportTransfers;
    }

    /**
     * Sets the value of the airportTransfers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportTransfers }
     *     
     */
    public void setAirportTransfers(AirportTransfers value) {
        this.airportTransfers = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the brandCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * Sets the value of the brandCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandCode(String value) {
        this.brandCode = value;
    }

    /**
     * Gets the value of the cmsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMSId() {
        return cmsId;
    }

    /**
     * Sets the value of the cmsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMSId(String value) {
        this.cmsId = value;
    }

    /**
     * Gets the value of the cmsTourId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMSTourId() {
        return cmsTourId;
    }

    /**
     * Sets the value of the cmsTourId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMSTourId(String value) {
        this.cmsTourId = value;
    }

    /**
     * Gets the value of the catalogueCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogueCode() {
        return catalogueCode;
    }

    /**
     * Sets the value of the catalogueCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogueCode(String value) {
        this.catalogueCode = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration(BigInteger value) {
        this.duration = value;
    }

    /**
     * Gets the value of the mvCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMVCode() {
        return mvCode;
    }

    /**
     * Sets the value of the mvCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMVCode(String value) {
        this.mvCode = value;
    }

    /**
     * Gets the value of the opCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPCode(String value) {
        this.opCode = value;
    }

}
