//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:04:24 PM CEST 
//


package com.ttsl.marketlocalisedtourdata._2010._11._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContinentCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContinentCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="AFRI"/>
 *     &lt;enumeration value="ANTA"/>
 *     &lt;enumeration value="ASIA"/>
 *     &lt;enumeration value="AUST"/>
 *     &lt;enumeration value="CAME"/>
 *     &lt;enumeration value="EURO"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="SAME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContinentCode")
@XmlEnum
public enum ContinentCode {

    AFRI,
    ANTA,
    ASIA,
    AUST,
    CAME,
    EURO,
    NAME,
    SAME;

    public String value() {
        return name();
    }

    public static ContinentCode fromValue(String v) {
        return valueOf(v);
    }

}
